### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by ruturaj-gh** [Srishti44-g/HACTOBERFEST-2022#18]
can i contribute by adding some sorting algorithms into your repository

**Comment by Srishti44-g** [comment]
yes you can ...please attach your program in DSA folder only

**Comment by ruturaj-gh** [comment]
![Uploading Screenshot_2022-10-10-21-20-54-29_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()
Mam I guess you haven't added hactoberfest label

**Comment by Srishti44-g** [comment]
follow rules:
1. Star my repo
2. Add some genuine programs 
3. Create valid pull requests
then only I can add any label
